name: CI/CD for Java Spring Boot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH connection with password
      run: |
        sshpass -p "${{ secrets.SSH_PASSPHRASE }}" ssh -o StrictHostKeyChecking=no root@${{ secrets.VM_IP }} 'cd ${{ secrets.REPO_PATH }} && git pull && mvn clean install && systemctl restart ${{ secrets.APP_SERVICE_NAME }}'
      env:
        SSHPASS: ${{ secrets.SSH_PASSPHRASE }}

    - name: Install sshpass
      run: sudo apt-get install -y sshpass

